{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "datasunrise.fullname" . }}
  labels:
    {{- include "datasunrise.labels" . | nindent 4 }}
rules:
{{- range .Values.rbac.rules }}
  - apiGroups: {{ (default (list "") .apiGroups) | toJson }}
    resources: {{ (default (list "") .resources) | toJson }}
    verbs: {{ (default (list "") .verbs) | toJson }}
{{- end }}
{{- end -}}
